import "./globals.css";
import Headers from "@/components/Section/Headers";
import { Inter } from "next/font/google";
import Footer from "@/components/Section/Footer";
import { Toaster } from "@/components/ui/sonner"
import StoreProvider from "@/redux/StoreProvider";
import InitalLoad from "@/components/Section/InitalLoad";
import NextTopLoader from "nextjs-toploader";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Strew",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} antialiased`}
      >
        <NextTopLoader 
          color="#e8c15a"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          showSpinner={false}
          zIndex={1600}
          showAtBottom={false}
        />
        <StoreProvider>
          <InitalLoad>
            <Headers/>
            <Toaster position="bottom-center" style={{
              "background": "black",
            }}/>
            {/* leave room for the desktop sidebar */}
            <div className="flex min-h-screen flex-col lg:pl-[76px]">
              <div className="flex-1">
                {children}
              </div>
              <Footer/>
            </div>
          </InitalLoad>
        </StoreProvider>
      </body>
    </html>
  );
}
